### PR TITLE
update docs to have error type information as well

### PR DESCRIPTION
**Pull request by karthik2804**

### CODE REVIEW

**Comment by karthik2804** [comment]
I am wondering if this should just be built in CI and deployed to pages as an artifact.

**Comment by radu-matei** [comment]
Oh yeah, doing this in CI would be great.

**Comment by karthik2804** [comment]
I assume we still want to keep the V1 docs as well. I have to take a look at how that will work.

**Comment by karthik2804** [comment]
Docs pushed to a seperate branch 
https://github.com/fermyon/spin-js-sdk/tree/gh_pages

**Pull request closed without merging**
