### PR TITLE
add MAINTAINERS.md file

### PR DESCRIPTION
**Pull request by michelleN**
+ Part of Spin governance follow up tasks: https://github.com/fermyon/spin/blob/main/GOVERNANCE.md?plain=1#L34

@radu-matei @ThorstenHans @vdice @dicej @karthik2804 - please let me know if I've forgotten anyone or if you'd like to not be on this list for any reason.

### CODE REVIEW

**Review by radu-matei — APPROVED** [review]

**Comment by karthik2804** [comment]
@michelleN I think it will need to be merged into the `feat/sdk-v2` branch since `main` will be replaced with that branch soon.

**Comment by radu-matei** [comment]
We can also cherry pick the commit into the v2 branch.

**Review by vdice — APPROVED** [review]

**Review by karthik2804 — APPROVED** [review]

**Comment by michelleN** [comment]
Is it alright to merge this even though CI is failing?

**Comment by karthik2804** [comment]
@michelleN It is good to merge.

**Pull request merged**
