### PR TITLE
Add snippets to enable `spin add`

### PR DESCRIPTION
**Pull request by radu-matei**
cc @itowlson 

Signed-off-by: Radu Matei <radu.matei@fermyon.com>

### CODE REVIEW

**Comment by karthik2804** [comment]
I run into an error when I try to add a TypeScript component but it succeeds when using a js-component.

```bash
# errors out
$ spin add http-ts test-component --accept-defaults
Error: liquid: Unknown variable
  with:
    requested variable=msg


# succeeds
$ spin add http-js test-component --accept-defaults
```

**Comment by radu-matei** [comment]
Make sure to uninstall the TS template before, I just re-ran `spin add` with a TypeScript component and everything seems to work fine for me.

**Comment by karthik2804** [comment]
That solved it! I had to install (update) the templates from your branch. This works as expected.
```bash
spin templates install --update --git https://github.com/radu-matei/spin-js-sdk/ --branch templates-add-component
```

I keep running into the same error when I try to install the templates from a local directory where the PR was checked out with the following command

```bash
spin templates install --update --dir ./
```

Not sure if this is an issue only on my end. I will take another look tomorrow.

**Review by itowlson — APPROVED** [review]
This looks fine in itself, and I'm happy for us to merge it.

But it would be good to modify the standard template to be consistent with the snippet, e.g. deriving `component.id` instead of fixing it to `hello`, deriving `component.trigger.route`.

Also, and I guess out of scope for this, for the standard template we should:

* Derive the application `name`
* Derive the application `trigger.base`

At the moment it looks like we prompt for these but don't actually use them, though I might be missing something - I've only read the `spin.toml` not tried running it.

I would also suggest that we consider building to something like `{{ project-name | kebab_case }}.wasm` rather than always `spin-http-js.wasm`, to make visual distinction easier if modules get copied around.  Not a big deal though, e.g. if the tooling that makes this onerous/impractical.

**Review by karthik2804 — APPROVED** [review]

**Comment by karthik2804** [comment]
@radu-matei Do you want to include the fixes to the template to derive `name`, `trigger.base` and `path` as pointed above or should I make a separate PR for that.

**Comment by karthik2804** [comment]
@radu-matei Do you want to include the fixes to the template to derive `name`, `trigger.base` and `path` as pointed above or should I make a separate PR for that.

**Comment by radu-matei** [comment]
Feel free to create a separate PR, @karthik2804!
Thanks!

**Pull request merged**
